import { registerCapabilities } from "./registry.js";

registerCapabilities([
  {
    module: "tenants",
    code: "tenants.me",
    name: "Ver mi tenant",
    description: "Información del tenant al que pertenece el usuario autenticado.",
    kind: "VISUALIZACION",
    dependencies: [],
  },
  {
    module: "tenants",
    code: "tenants.meCapabilities",
    name: "Ver mis capacidades",
    description: "Capacidades efectivas del plan actual del tenant autenticado.",
    kind: "VISUALIZACION",
    dependencies: [{ code: "tenants.me", type: "OBLIGATORIA" }],
  },
  {
    module: "tenants",
    code: "tenants.meUsage",
    name: "Ver mi consumo",
    description: "Uso de recursos del tenant (límites y consumo vigente).",
    kind: "ANALISIS",
    dependencies: [{ code: "tenants.me", type: "OBLIGATORIA" }],
  },
  {
    module: "tenants",
    code: "tenants.dashboard",
    name: "Dashboard del tenant",
    description:
      "Resumen administrativo del tenant (usuarios, canales y consumo).",
    kind: "ANALISIS",
    dependencies: [{ code: "tenants.me", type: "OBLIGATORIA" }],
  },
  {
    module: "tenants",
    code: "tenants.updateMe",
    name: "Editar mi tenant",
    description: "Actualizar datos propios del tenant (nombre, configuración básica).",
    kind: "EDICION",
    dependencies: [{ code: "tenants.me", type: "OBLIGATORIA" }],
  },
  {
    module: "tenants",
    code: "tenants.view",
    name: "Listar tenants",
    description: "Lista/pagina todos los tenants registrados (super admin).",
    kind: "VISUALIZACION",
    dependencies: [],
  },
  {
    module: "tenants",
    code: "tenants.detail",
    name: "Ver detalle de tenant",
    description: "Detalle completo de un tenant, incluyendo usuarios y suscripción.",
    kind: "VISUALIZACION",
    dependencies: [{ code: "tenants.view", type: "OBLIGATORIA" }],
  },
  {
    module: "tenants",
    code: "tenants.create",
    name: "Crear tenant",
    description: "Registrar un tenant nuevo en la plataforma.",
    kind: "CREACION",
    dependencies: [{ code: "tenants.view", type: "OBLIGATORIA" }],
  },
  {
    module: "tenants",
    code: "tenants.update",
    name: "Editar tenant",
    description: "Editar datos de un tenant (super admin).",
    kind: "EDICION",
    dependencies: [{ code: "tenants.detail", type: "OBLIGATORIA" }],
  },
  {
    module: "tenants",
    code: "tenants.changePlan",
    name: "Cambiar plan de tenant",
    description: "Asignar o cambiar el plan de suscripción de un tenant.",
    kind: "CAMBIO_ESTADO",
    dependencies: [{ code: "tenants.detail", type: "OBLIGATORIA" }],
  },
  {
    module: "tenants",
    code: "tenants.changeStatus",
    name: "Cambiar estado de tenant",
    description: "Activar/suspender un tenant (cambio de estado de la cuenta).",
    kind: "SEGURIDAD",
    dependencies: [{ code: "tenants.detail", type: "OBLIGATORIA" }],
  },
]);
