import { registerCapabilities } from "./registry.js";
import {
  ALL_PLANS,
  ROLES_ANY_TENANT_USER,
  ROLES_SUPER_ADMIN,
  ROLES_TENANT_ADMIN,
} from "./presets.js";

registerCapabilities([
  {
    module: "tenants",
    code: "tenants.me",
    domain: "ADMINISTRATION",
    allowedRoles: ROLES_ANY_TENANT_USER,
    includedInPlans: ALL_PLANS,
    name: "Ver mi tenant",
    description: "Información del tenant al que pertenece el usuario autenticado.",
    kind: "VISUALIZACION",
    dependencies: [],
  },
  {
    module: "tenants",
    code: "tenants.meCapabilities",
    domain: "ADMINISTRATION",
    allowedRoles: ROLES_ANY_TENANT_USER,
    includedInPlans: ALL_PLANS,
    name: "Ver mis capacidades",
    description: "Capacidades efectivas del plan actual del tenant autenticado.",
    kind: "VISUALIZACION",
    dependencies: [
      { code: "tenants.me", type: "OBLIGATORIA" },
    ],
  },
  {
    module: "tenants",
    code: "tenants.meUsage",
    domain: "ADMINISTRATION",
    allowedRoles: ROLES_ANY_TENANT_USER,
    includedInPlans: ALL_PLANS,
    name: "Ver mi consumo",
    description: "Uso de recursos del tenant (límites y consumo vigente).",
    kind: "ANALISIS",
    dependencies: [
      { code: "tenants.me", type: "OBLIGATORIA" },
    ],
  },
  {
    module: "tenants",
    code: "tenants.dashboard",
    domain: "ADMINISTRATION",
    allowedRoles: ROLES_TENANT_ADMIN,
    includedInPlans: ALL_PLANS,
    name: "Dashboard del tenant",
    description: "Resumen administrativo del tenant (usuarios, canales y consumo).",
    kind: "ANALISIS",
    dependencies: [
      { code: "tenants.me", type: "OBLIGATORIA" },
    ],
  },
  {
    module: "tenants",
    code: "tenants.updateMe",
    domain: "ADMINISTRATION",
    allowedRoles: ROLES_ANY_TENANT_USER,
    includedInPlans: ALL_PLANS,
    name: "Editar mi tenant",
    description: "Actualizar datos propios del tenant (nombre, configuración básica).",
    kind: "EDICION",
    dependencies: [
      { code: "tenants.me", type: "OBLIGATORIA" },
    ],
  },
  {
    module: "tenants",
    code: "tenants.view",
    domain: "SUPER_ADMIN",
    allowedRoles: ROLES_SUPER_ADMIN,
    includedInPlans: ALL_PLANS,
    name: "Listar tenants",
    description: "Lista/pagina todos los tenants registrados (super admin).",
    kind: "VISUALIZACION",
    dependencies: [],
  },
  {
    module: "tenants",
    code: "tenants.detail",
    domain: "SUPER_ADMIN",
    allowedRoles: ROLES_SUPER_ADMIN,
    includedInPlans: ALL_PLANS,
    name: "Ver detalle de tenant",
    description: "Detalle completo de un tenant, incluyendo usuarios y suscripción.",
    kind: "VISUALIZACION",
    dependencies: [
      { code: "tenants.view", type: "OBLIGATORIA" },
    ],
  },
  {
    module: "tenants",
    code: "tenants.create",
    domain: "SUPER_ADMIN",
    allowedRoles: ROLES_SUPER_ADMIN,
    includedInPlans: ALL_PLANS,
    name: "Crear tenant",
    description: "Registrar un tenant nuevo en la plataforma.",
    kind: "CREACION",
    dependencies: [
      { code: "tenants.view", type: "OBLIGATORIA" },
    ],
  },
  {
    module: "tenants",
    code: "tenants.update",
    domain: "SUPER_ADMIN",
    allowedRoles: ROLES_SUPER_ADMIN,
    includedInPlans: ALL_PLANS,
    name: "Editar tenant",
    description: "Editar datos de un tenant (super admin).",
    kind: "EDICION",
    dependencies: [
      { code: "tenants.detail", type: "OBLIGATORIA" },
    ],
  },
  {
    module: "tenants",
    code: "tenants.changePlan",
    domain: "SUPER_ADMIN",
    allowedRoles: ROLES_SUPER_ADMIN,
    includedInPlans: ALL_PLANS,
    name: "Cambiar plan de tenant",
    description: "Asignar o cambiar el plan de suscripción de un tenant.",
    kind: "CAMBIO_ESTADO",
    dependencies: [
      { code: "tenants.detail", type: "OBLIGATORIA" },
    ],
  },
  {
    module: "tenants",
    code: "tenants.changeStatus",
    domain: "SUPER_ADMIN",
    allowedRoles: ROLES_SUPER_ADMIN,
    includedInPlans: ALL_PLANS,
    name: "Cambiar estado de tenant",
    description: "Activar/suspender un tenant (cambio de estado de la cuenta).",
    kind: "SEGURIDAD",
    dependencies: [
      { code: "tenants.detail", type: "OBLIGATORIA" },
    ],
  },
]);
