import type {
  CapabilityDependencyType,
  CapabilityKind,
  CapabilityStatus,
} from "../models/AppCapability.js";

export interface ICapabilityDependencyDTO {
  code: string;
  type: CapabilityDependencyType;
}

export interface IAppCapabilityDTO {
  module: string;
  code: string;
  name: string;
  description: string;
  kind: CapabilityKind;
  configurableByPlan: boolean;
  nonConfigurableReason?: string;
  dependencies: ICapabilityDependencyDTO[];
  evidence: string;
  status: CapabilityStatus;
  isActive: boolean;
  sortOrder: number;
}

const OBLIGATORIA: CapabilityDependencyType = "OBLIGATORIA";
const FUNCIONAL: CapabilityDependencyType = "FUNCIONAL";
const TECNICA: CapabilityDependencyType = "TECNICA";
const CONFIGURACION: CapabilityDependencyType = "CONFIGURACION";

// Inventario maestro de capacidades de QuoPilot (Nivel 1).
// Solo capacidades reales detectadas en la aplicación (rutas API, páginas web
// y tools del agente comercial). Las capacidades administrativas/técnicas se
// marcan como NO configurables por plan con su razón.
export const APP_CAPABILITIES_REGISTRY: IAppCapabilityDTO[] = [
  // ── MÓDULO DASHBOARD ─────────────────────────────────────────────
  {
    module: "dashboard",
    code: "dashboard.view",
    name: "Ver panel de KPIs",
    description: "Resumen de métricas del negocio: conteos, moneda y tasa de conversión.",
    kind: "ANALISIS",
    configurableByPlan: true,
    dependencies: [],
    evidence: "GET /api/dashboard/summary, /api/tenant|agent|super-admin/dashboard/summary; src/pages/Dashboard.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "dashboard",
    code: "reports.view",
    name: "Módulo de reportes",
    description: "No existe página de reportes; los KPIs del dashboard son lo más cercano.",
    kind: "ANALISIS",
    configurableByPlan: true,
    dependencies: [],
    evidence: "Feature 'reports' en AppFeature sin módulo propio; solo KPIs en Dashboard.tsx",
    status: "POR_CONFIRMAR",
    isActive: true,
    sortOrder: 2,
  },

  // ── MÓDULO CUSTOMERS ─────────────────────────────────────────────
  {
    module: "customers",
    code: "customers.view",
    name: "Listar clientes",
    description: "Lista/pagina clientes con búsqueda y filtro por país.",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "GET /api/customers; src/pages/Customers.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "customers",
    code: "customers.detail",
    name: "Ver ficha de cliente",
    description: "Detalle completo de un cliente (contacto, facturación, identificación).",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [{ code: "customers.view", type: OBLIGATORIA }],
    evidence: "GET /api/customers/:id; src/pages/CustomerDetail.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 2,
  },
  {
    module: "customers",
    code: "customers.create",
    name: "Crear cliente",
    description: "Registrar un cliente nuevo (empresa o persona).",
    kind: "CREACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "POST /api/customers",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 3,
  },
  {
    module: "customers",
    code: "customers.update",
    name: "Editar cliente",
    description: "Modificar datos de un cliente existente.",
    kind: "EDICION",
    configurableByPlan: true,
    dependencies: [{ code: "customers.view", type: OBLIGATORIA }],
    evidence: "PATCH /api/customers/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 4,
  },
  {
    module: "customers",
    code: "customers.delete",
    name: "Eliminar cliente",
    description: "Eliminar un cliente del tenant.",
    kind: "ELIMINACION",
    configurableByPlan: true,
    dependencies: [{ code: "customers.view", type: OBLIGATORIA }],
    evidence: "DELETE /api/customers/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 5,
  },
  {
    module: "customers",
    code: "customers.history",
    name: "Consultar historial comercial",
    description: "Historial del cliente: ventas confirmadas, cotizaciones abiertas, última compra.",
    kind: "CONSULTA",
    configurableByPlan: true,
    dependencies: [
      { code: "customers.view", type: OBLIGATORIA },
      { code: "sales.view", type: FUNCIONAL },
    ],
    evidence: "Tool getCustomerHistory (agent-tools/customer-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 6,
  },

  // ── MÓDULO PRODUCTS ──────────────────────────────────────────────
  {
    module: "products",
    code: "products.view",
    name: "Listar productos",
    description: "Lista/pagina productos, servicios y combos con filtros.",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "GET /api/products; src/pages/Products.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "products",
    code: "products.detail",
    name: "Ver ficha de producto",
    description: "Detalle completo: precios, listas de precio, bodegas, impuestos, imagen.",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [{ code: "products.view", type: OBLIGATORIA }],
    evidence: "GET /api/products/:id; src/pages/ProductDetail.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 2,
  },
  {
    module: "products",
    code: "products.create",
    name: "Crear producto",
    description: "Crear producto/servicio/combo, incluida el alta rápida.",
    kind: "CREACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "POST /api/products; ProductQuickModal.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 3,
  },
  {
    module: "products",
    code: "products.update",
    name: "Editar producto",
    description: "Modificar un producto (precios, impuestos, bodegas, imagen).",
    kind: "EDICION",
    configurableByPlan: true,
    dependencies: [{ code: "products.view", type: OBLIGATORIA }],
    evidence: "PATCH /api/products/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 4,
  },
  {
    module: "products",
    code: "products.changeStatus",
    name: "Activar/desactivar producto",
    description: "Cambiar el estado ACTIVO/INACTIVO de un producto.",
    kind: "CAMBIO_ESTADO",
    configurableByPlan: true,
    dependencies: [{ code: "products.view", type: OBLIGATORIA }],
    evidence: "PATCH /api/products/:id/status",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 5,
  },
  {
    module: "products",
    code: "products.delete",
    name: "Eliminar producto",
    description: "Eliminar un producto del catálogo.",
    kind: "ELIMINACION",
    configurableByPlan: true,
    dependencies: [{ code: "products.view", type: OBLIGATORIA }],
    evidence: "DELETE /api/products/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 6,
  },

  // ── MÓDULO QUOTES ────────────────────────────────────────────────
  {
    module: "quotes",
    code: "quotes.view",
    name: "Listar cotizaciones",
    description: "Lista/pagina cotizaciones con filtros por estado, cliente y búsqueda.",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "GET /api/quotes; src/pages/Quotes.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "quotes",
    code: "quotes.detail",
    name: "Ver detalle de cotización",
    description: "Detalle completo, ítems y eventos/historial de la cotización.",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [{ code: "quotes.view", type: OBLIGATORIA }],
    evidence: "GET /api/quotes/:id; src/pages/QuoteDetail.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 2,
  },
  {
    module: "quotes",
    code: "quotes.create",
    name: "Crear cotización",
    description: "Crear una cotización en borrador con cliente e ítems.",
    kind: "CREACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "POST /api/quotes; src/pages/CreateQuote.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 3,
  },
  {
    module: "quotes",
    code: "quotes.update",
    name: "Editar cotización",
    description: "Modificar ítems y datos de una cotización.",
    kind: "EDICION",
    configurableByPlan: true,
    dependencies: [
      { code: "quotes.view", type: OBLIGATORIA },
      { code: "quotes.create", type: FUNCIONAL },
    ],
    evidence: "PATCH /api/quotes/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 4,
  },
  {
    module: "quotes",
    code: "quotes.send",
    name: "Enviar cotización",
    description: "Entregar la cotización al cliente (marcar como enviada).",
    kind: "OPERACION_COMERCIAL",
    configurableByPlan: true,
    dependencies: [{ code: "quotes.detail", type: OBLIGATORIA }],
    evidence: "POST /api/quotes/:id/send",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 5,
  },
  {
    module: "quotes",
    code: "quotes.accept",
    name: "Aceptar cotización",
    description: "Aceptar una cotización enviada; genera automáticamente la venta.",
    kind: "OPERACION_COMERCIAL",
    configurableByPlan: true,
    dependencies: [{ code: "quotes.send", type: OBLIGATORIA }],
    evidence: "POST /api/quotes/:id/accept",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 6,
  },
  {
    module: "quotes",
    code: "quotes.pdf",
    name: "Descargar cotización PDF",
    description: "Generar y descargar el documento PDF de la cotización.",
    kind: "DOCUMENTO",
    configurableByPlan: true,
    dependencies: [{ code: "quotes.detail", type: OBLIGATORIA }],
    evidence: "usePdfDownload + components/pdf/QuotePdf.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 7,
  },

  // ── MÓDULO SALES ─────────────────────────────────────────────────
  {
    module: "sales",
    code: "sales.view",
    name: "Listar ventas",
    description: "Lista/pagina ventas con filtros por estado, cliente, producto y fechas.",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "GET /api/sales; src/pages/Sales.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "sales",
    code: "sales.detail",
    name: "Ver detalle de venta",
    description: "Detalle completo de una venta con su cotización y eventos.",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [{ code: "sales.view", type: OBLIGATORIA }],
    evidence: "GET /api/sales/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 2,
  },
  {
    module: "sales",
    code: "sales.cancel",
    name: "Cancelar venta",
    description: "Cancelar una venta confirmada.",
    kind: "OPERACION_COMERCIAL",
    configurableByPlan: true,
    dependencies: [{ code: "sales.detail", type: OBLIGATORIA }],
    evidence: "POST /api/sales/:id/cancel",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 3,
  },
  {
    module: "sales",
    code: "sales.delete",
    name: "Eliminar venta",
    description: "Eliminar una venta (solo si está cancelada).",
    kind: "ELIMINACION",
    configurableByPlan: true,
    dependencies: [{ code: "sales.cancel", type: FUNCIONAL }],
    evidence: "DELETE /api/sales/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 4,
  },
  {
    module: "sales",
    code: "sales.pdf",
    name: "Descargar venta PDF",
    description: "Generar y descargar el documento PDF de la venta.",
    kind: "DOCUMENTO",
    configurableByPlan: true,
    dependencies: [{ code: "sales.detail", type: OBLIGATORIA }],
    evidence: "components/pdf/SalePdf.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 5,
  },

  // ── MÓDULO CHANNELS ──────────────────────────────────────────────
  {
    module: "channels",
    code: "channels.view",
    name: "Listar canales",
    description: "Lista canales de comunicación (WhatsApp, Web Chat, Instagram).",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "GET /api/channels; src/pages/Channels.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "channels",
    code: "channels.detail",
    name: "Ver configuración de canal",
    description: "Detalle de la configuración de un canal.",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [{ code: "channels.view", type: OBLIGATORIA }],
    evidence: "GET /api/channels/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 2,
  },
  {
    module: "channels",
    code: "channels.create",
    name: "Crear canal",
    description: "Crear un canal con credenciales (WhatsApp/Instagram/Web Chat).",
    kind: "CREACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "POST /api/channels; src/pages/ChannelForm.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 3,
  },
  {
    module: "channels",
    code: "channels.update",
    name: "Editar canal",
    description: "Modificar la configuración de un canal.",
    kind: "EDICION",
    configurableByPlan: true,
    dependencies: [{ code: "channels.view", type: OBLIGATORIA }],
    evidence: "PATCH /api/channels/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 4,
  },
  {
    module: "channels",
    code: "channels.changeStatus",
    name: "Activar/desactivar canal",
    description: "Cambiar el estado ACTIVO/INACTIVO de un canal.",
    kind: "CAMBIO_ESTADO",
    configurableByPlan: true,
    dependencies: [{ code: "channels.view", type: OBLIGATORIA }],
    evidence: "PATCH /api/channels/:id/status",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 5,
  },
  {
    module: "channels",
    code: "channels.delete",
    name: "Eliminar canal",
    description: "Eliminar un canal de comunicación.",
    kind: "ELIMINACION",
    configurableByPlan: true,
    dependencies: [{ code: "channels.view", type: OBLIGATORIA }],
    evidence: "DELETE /api/channels/:id",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 6,
  },
  {
    module: "channels",
    code: "channels.publicChat",
    name: "Widget de chat público",
    description: "Widget embebible de chat con el agente desde el sitio web del cliente.",
    kind: "COMUNICACION",
    configurableByPlan: true,
    dependencies: [
      { code: "channels.view", type: OBLIGATORIA },
      { code: "agent.configure", type: TECNICA },
    ],
    evidence: "/api/agent/public/chat/*; src/pages/PublicChat.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 7,
  },
  {
    module: "channels",
    code: "channels.webhookUrl",
    name: "Consultar URL de webhook",
    description: "Copiar/consultar la URL del webhook de un canal.",
    kind: "TECNICA",
    configurableByPlan: false,
    nonConfigurableReason: "Infraestructura técnica del canal; no es una capacidad comercial.",
    dependencies: [],
    evidence: "src/pages/Channels.tsx (copiar URL); webhook-routes.ts",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 8,
  },

  // ── MÓDULO CONVERSATIONS ─────────────────────────────────────────
  {
    module: "conversations",
    code: "conversations.view",
    name: "Ver bandeja de conversaciones",
    description: "Bandeja de entrada con filtros por canal, estado y asignación.",
    kind: "VISUALIZACION",
    configurableByPlan: true,
    dependencies: [{ code: "channels.view", type: FUNCIONAL }],
    evidence: "GET /api/conversations; src/pages/Conversations.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "conversations",
    code: "conversations.messages",
    name: "Leer mensajes",
    description: "Leer los mensajes de una conversación.",
    kind: "CONSULTA",
    configurableByPlan: true,
    dependencies: [{ code: "conversations.view", type: OBLIGATORIA }],
    evidence: "GET /api/conversations/:id/messages",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 2,
  },
  {
    module: "conversations",
    code: "conversations.reply",
    name: "Responder mensaje",
    description: "Enviar una respuesta en una conversación.",
    kind: "COMUNICACION",
    configurableByPlan: true,
    dependencies: [{ code: "conversations.messages", type: OBLIGATORIA }],
    evidence: "POST /api/conversations/:id/reply",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 3,
  },
  {
    module: "conversations",
    code: "conversations.claim",
    name: "Reclamar conversación",
    description: "Asignar/tomar una conversación para atenderla.",
    kind: "OPERACION_COMERCIAL",
    configurableByPlan: true,
    dependencies: [{ code: "conversations.view", type: OBLIGATORIA }],
    evidence: "POST /api/conversations/:id/claim",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 4,
  },
  {
    module: "conversations",
    code: "conversations.reopen",
    name: "Reabrir conversación",
    description: "Reabrir una conversación cerrada.",
    kind: "OPERACION_COMERCIAL",
    configurableByPlan: true,
    dependencies: [{ code: "conversations.view", type: OBLIGATORIA }],
    evidence: "POST /api/conversations/:id/reopen",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 5,
  },
  {
    module: "conversations",
    code: "conversations.typing",
    name: "Indicador escribiendo",
    description: "Estado de escritura en las conversaciones.",
    kind: "TECNICA",
    configurableByPlan: false,
    nonConfigurableReason: "Detalle técnico de tiempo real; no es una capacidad comercial.",
    dependencies: [],
    evidence: "GET/POST /api/conversations/:id/typing",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 6,
  },

  // ── MÓDULO AGENT ─────────────────────────────────────────────────
  {
    module: "agent",
    code: "agent.configure",
    name: "Configurar agente IA",
    description: "Configuración del agente comercial: personalidad, tono, LLM, tools, alcance de productos.",
    kind: "CONFIGURACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "GET/PATCH /api/agent/config; src/pages/AgentConfig.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "agent",
    code: "agent.chat",
    name: "Chat con clientes",
    description: "Abrir y mantener conversaciones con clientes a través del agente.",
    kind: "COMUNICACION",
    configurableByPlan: true,
    dependencies: [
      { code: "agent.configure", type: TECNICA },
      { code: "channels.view", type: FUNCIONAL },
    ],
    evidence: "POST /api/agent/conversations; src/pages/AgentChat.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 2,
  },
  {
    module: "agent",
    code: "agent.productSearch",
    name: "Agente: buscar productos",
    description: "El agente consulta el catálogo de productos para atender al cliente.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "products.view", type: OBLIGATORIA }],
    evidence: "Tool searchProducts (agent-tools/product-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 3,
  },
  {
    module: "agent",
    code: "agent.productDetails",
    name: "Agente: ficha de producto",
    description: "El agente consulta la ficha completa de un producto.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "products.detail", type: OBLIGATORIA }],
    evidence: "Tool getProductDetails (agent-tools/product-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 4,
  },
  {
    module: "agent",
    code: "agent.customerLookup",
    name: "Agente: buscar cliente",
    description: "El agente busca clientes del tenant.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "customers.view", type: OBLIGATORIA }],
    evidence: "Tool searchCustomers (agent-tools/customer-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 5,
  },
  {
    module: "agent",
    code: "agent.customerHistory",
    name: "Agente: historial del cliente",
    description: "El agente consulta el historial comercial del cliente.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "customers.history", type: OBLIGATORIA }],
    evidence: "Tool getCustomerHistory (agent-tools/customer-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 6,
  },
  {
    module: "agent",
    code: "agent.customerUpdate",
    name: "Agente: actualizar cliente",
    description: "El agente actualiza datos básicos del cliente.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "customers.update", type: OBLIGATORIA }],
    evidence: "Tool updateCustomer (agent-tools/customer-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 7,
  },
  {
    module: "agent",
    code: "agent.quoteHistory",
    name: "Agente: historial de cotizaciones",
    description: "El agente consulta el historial de cotizaciones del cliente.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "quotes.view", type: OBLIGATORIA }],
    evidence: "Tool getQuotes (agent-tools/quote-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 8,
  },
  {
    module: "agent",
    code: "agent.quoteDetails",
    name: "Agente: estado de cotización",
    description: "El agente consulta el estado y totales de una cotización.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "quotes.detail", type: OBLIGATORIA }],
    evidence: "Tool getQuoteStatus (agent-tools/quote-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 9,
  },
  {
    module: "agent",
    code: "agent.quoteDraft",
    name: "Agente: crear borrador de cotización",
    description: "El agente crea una cotización en borrador vinculada a la conversación.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "quotes.create", type: OBLIGATORIA }],
    evidence: "Tool createQuote (agent-tools/quote-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 10,
  },
  {
    module: "agent",
    code: "agent.quoteUpdate",
    name: "Agente: modificar borrador de cotización",
    description: "El agente modifica una cotización en borrador.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "agent.quoteDraft", type: FUNCIONAL }],
    evidence: "Tool updateQuote (agent-tools/quote-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 11,
  },
  {
    module: "agent",
    code: "agent.quoteAccept",
    name: "Agente: aceptar cotización",
    description: "El agente acepta una cotización y genera la venta.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "quotes.accept", type: OBLIGATORIA }],
    evidence: "Tool acceptQuote (agent-tools/quote-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 12,
  },
  {
    module: "agent",
    code: "agent.salesHistory",
    name: "Agente: consultar ventas",
    description: "El agente consulta las ventas del cliente.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "sales.view", type: OBLIGATORIA }],
    evidence: "Tool getSales (agent-tools/sales-tools.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 13,
  },
  {
    module: "agent",
    code: "agent.humanHandoff",
    name: "Agente: escalar a humano",
    description: "El agente escala la conversación a un agente humano.",
    kind: "IA",
    configurableByPlan: true,
    dependencies: [{ code: "agent.chat", type: OBLIGATORIA }],
    evidence: "Tool requestHumanHandoff (agent-tools/handoff-tool.ts)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 14,
  },
  {
    module: "agent",
    code: "agent.assistantConfig",
    name: "Asistente IA de configuración del agente",
    description: "Asistente que ayuda a configurar el agente por lenguaje natural.",
    kind: "TECNICA",
    configurableByPlan: false,
    nonConfigurableReason: "Herramienta administrativa de soporte; no es una capacidad comercial.",
    dependencies: [],
    evidence: "/api/agent/assistant/*; src/services/agent-config-assistant.ts",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 15,
  },

  // ── MÓDULO SETTINGS ──────────────────────────────────────────────
  {
    module: "settings",
    code: "settings.company",
    name: "Datos fiscales de la empresa",
    description: "Editar NIT, dirección, ciudad, país y demás datos fiscales.",
    kind: "CONFIGURACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "PATCH /api/tenants/me; src/pages/CompanySettings.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "settings",
    code: "settings.currency",
    name: "Definir moneda",
    description: "Seleccionar la moneda de operación del tenant.",
    kind: "CONFIGURACION",
    configurableByPlan: true,
    dependencies: [{ code: "settings.company", type: OBLIGATORIA }],
    evidence: "src/pages/CompanySettings.tsx (lista Intl)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 2,
  },
  {
    module: "settings",
    code: "settings.timezone",
    name: "Definir zona horaria",
    description: "Seleccionar la zona horaria del tenant.",
    kind: "CONFIGURACION",
    configurableByPlan: true,
    dependencies: [{ code: "settings.company", type: OBLIGATORIA }],
    evidence: "src/pages/CompanySettings.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 3,
  },
  {
    module: "settings",
    code: "settings.branding",
    name: "Marca y logo",
    description: "Logo, color de marca y pie de documentos.",
    kind: "CONFIGURACION",
    configurableByPlan: true,
    dependencies: [{ code: "settings.company", type: OBLIGATORIA }],
    evidence: "src/pages/CompanySettings.tsx (ImageUploader)",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 4,
  },
  {
    module: "settings",
    code: "settings.commercialPolicy",
    name: "Política comercial",
    description: "Configurar pagos, descuentos, envíos, garantía y devoluciones.",
    kind: "CONFIGURACION",
    configurableByPlan: true,
    dependencies: [{ code: "settings.company", type: OBLIGATORIA }],
    evidence: "Modelo CommercialPolicy; tools get/updateCommercialPolicy (asistente interno)",
    status: "POR_CONFIRMAR",
    isActive: true,
    sortOrder: 5,
  },
  {
    module: "settings",
    code: "integrations.manage",
    name: "Módulo de integraciones",
    description: "Gestión de integraciones externas (API, webhooks). Hoy cubierto por canales.",
    kind: "CONFIGURACION",
    configurableByPlan: true,
    dependencies: [],
    evidence: "Feature 'integrations' en AppFeature sin módulo propio; solo canales y webhooks de entrada",
    status: "POR_CONFIRMAR",
    isActive: true,
    sortOrder: 6,
  },

  // ── MÓDULOS ADMINISTRATIVOS / NO CONFIGURABLES ──────────────────
  {
    module: "auth",
    code: "auth.login",
    name: "Iniciar sesión",
    description: "Autenticación de usuarios del tenant.",
    kind: "AUTENTICACION",
    configurableByPlan: false,
    nonConfigurableReason: "Seguridad y acceso fundamental del sistema.",
    dependencies: [],
    evidence: "POST /api/auth/login",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "auth",
    code: "auth.changePassword",
    name: "Cambiar contraseña",
    description: "Cambio de contraseña del usuario autenticado.",
    kind: "SEGURIDAD",
    configurableByPlan: false,
    nonConfigurableReason: "Seguridad fundamental del sistema.",
    dependencies: [],
    evidence: "POST /api/auth/change-password",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 2,
  },
  {
    module: "tenants",
    code: "tenants.manage",
    name: "Gestión de empresas (Super Admin)",
    description: "Crear, editar, activar/desactivar tenants y ver sus usuarios.",
    kind: "ADMINISTRACION",
    configurableByPlan: false,
    nonConfigurableReason: "Administración de la plataforma, exclusiva de SUPER_ADMIN.",
    dependencies: [],
    evidence: "/api/tenants/*; src/pages/Tenants.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "users",
    code: "users.manage",
    name: "Gestión de agentes del tenant",
    description: "Crear, editar, activar/desactivar y eliminar usuarios/agentes del tenant.",
    kind: "ADMINISTRACION",
    configurableByPlan: false,
    nonConfigurableReason: "Administrativo del tenant; candidato a límite comercial (nº de agentes), no a capacidad.",
    dependencies: [],
    evidence: "/api/users/*; src/pages/Users.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "plans",
    code: "plans.manage",
    name: "Gestión de planes",
    description: "Crear, editar, eliminar planes y definir features/capacidades por plan.",
    kind: "ADMINISTRACION",
    configurableByPlan: false,
    nonConfigurableReason: "Es la herramienta misma de configuración; exclusiva de SUPER_ADMIN.",
    dependencies: [],
    evidence: "/api/super-admin/plans/*; src/pages/Plans.tsx",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "catalog",
    code: "catalog.manage",
    name: "Gestión de catálogo",
    description: "Listar features/herramientas IA y sincronizar el catálogo.",
    kind: "ADMINISTRACION",
    configurableByPlan: false,
    nonConfigurableReason: "Técnico/interno de la plataforma.",
    dependencies: [],
    evidence: "/api/admin/features, /ai-tools, /sync-catalog",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "assistantCapabilities",
    code: "assistantCapabilities.manage",
    name: "Config de capacidades del asistente",
    description: "Definir toolPermissions (Nivel 2) por plan para el asistente interno.",
    kind: "ADMINISTRACION",
    configurableByPlan: false,
    nonConfigurableReason: "Capa de configuración del asistente interno; exclusiva de SUPER_ADMIN.",
    dependencies: [],
    evidence: "/api/super-admin/assistant-capabilities/*",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "webhooks",
    code: "webhooks.receive",
    name: "Recepción de webhooks",
    description: "Endpoints de entrada de WhatsApp/Instagram con verificación HMAC.",
    kind: "SEGURIDAD",
    configurableByPlan: false,
    nonConfigurableReason: "Técnico/seguridad de integración; se activa con el canal correspondiente.",
    dependencies: [],
    evidence: "GET/POST /api/webhooks/:type/:channelId",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "internalAssistant",
    code: "internalAssistant.manage",
    name: "Asistente interno de administración",
    description: "Asistente interno del panel que ayuda al administrador del tenant.",
    kind: "TECNICA",
    configurableByPlan: false,
    nonConfigurableReason: "Herramienta administrativa de soporte interno.",
    dependencies: [],
    evidence: "/api/internal/assistant/*; src/services/internal-tenant-assistant.ts",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
  {
    module: "supportAssistant",
    code: "supportAssistant.manage",
    name: "Config global del asistente de soporte",
    description: "Configuración global (LLM, prompt, umbrales) del asistente interno de soporte.",
    kind: "ADMINISTRACION",
    configurableByPlan: false,
    nonConfigurableReason: "Configuración global del asistente; exclusiva de SUPER_ADMIN.",
    dependencies: [],
    evidence: "/api/super-admin/support/assistant/config",
    status: "ACTIVE",
    isActive: true,
    sortOrder: 1,
  },
];