export interface IAppFeatureDTO {
  key: string;
  label: string;
  description: string;
  category: string;
  isActive: boolean;
  sortOrder: number;
  metadata?: Record<string, unknown>;
}

export const APP_FEATURES_REGISTRY: IAppFeatureDTO[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    description: "Panel principal de métricas y KPIs",
    category: "general",
    isActive: true,
    sortOrder: 1,
    metadata: {},
  },
  {
    key: "customers",
    label: "Clientes",
    description: "Gestión de clientes y contactos",
    category: "comercial",
    isActive: true,
    sortOrder: 2,
    metadata: {},
  },
  {
    key: "products",
    label: "Productos",
    description: "Catálogo de productos y servicios",
    category: "comercial",
    isActive: true,
    sortOrder: 3,
    metadata: {},
  },
  {
    key: "quotes",
    label: "Cotizaciones",
    description: "Creación y gestión de cotizaciones",
    category: "comercial",
    isActive: true,
    sortOrder: 4,
    metadata: {},
  },
  {
    key: "sales",
    label: "Ventas",
    description: "Pipeline y registro de ventas",
    category: "comercial",
    isActive: true,
    sortOrder: 5,
    metadata: {},
  },
  {
    key: "channels",
    label: "Canales",
    description: "Canales de comunicación (WhatsApp, Web Chat, etc.)",
    category: "canales",
    isActive: true,
    sortOrder: 6,
    metadata: {},
  },
  {
    key: "conversations",
    label: "Conversaciones",
    description: "Bandeja de conversaciones y mensajería en vivo",
    category: "canales",
    isActive: true,
    sortOrder: 7,
    metadata: {},
  },
  {
    key: "agent",
    label: "Agente IA",
    description: "Configuración del agente comercial",
    category: "ia",
    isActive: true,
    sortOrder: 8,
    metadata: {},
  },
  {
    key: "reports",
    label: "Reportes",
    description: "Reportes y analytics",
    category: "analytics",
    isActive: true,
    sortOrder: 9,
    metadata: {},
  },
  {
    key: "integrations",
    label: "Integraciones",
    description: "API, webhooks e integraciones externas",
    category: "integraciones",
    isActive: true,
    sortOrder: 10,
    metadata: {},
  },
  {
    key: "settings",
    label: "Configuración",
    description: "Configuración general del tenant",
    category: "configuracion",
    isActive: true,
    sortOrder: 11,
    metadata: {},
  },
  {
    key: "auth",
    label: "Autenticación",
    description: "Acceso, inicio de sesión y seguridad de cuenta",
    category: "general",
    isActive: true,
    sortOrder: 12,
    metadata: {},
  },
  {
    key: "tenants",
    label: "Tenants",
    description: "Gestión de empresas/tenants y suscripciones",
    category: "administracion",
    isActive: true,
    sortOrder: 13,
    metadata: {},
  },
  {
    key: "users",
    label: "Usuarios",
    description: "Gestión de usuarios y agentes del tenant",
    category: "administracion",
    isActive: true,
    sortOrder: 14,
    metadata: {},
  },
  {
    key: "webhooks",
    label: "Webhooks",
    description: "Recepción de eventos de canales de mensajería",
    category: "integraciones",
    isActive: true,
    sortOrder: 17,
    metadata: {},
  },
  {
    key: "internalAssistant",
    label: "Asistente interno",
    description: "Asistente IA interno para super administradores",
    category: "ia",
    isActive: true,
    sortOrder: 18,
    metadata: {},
  },
  {
    key: "supportAssistant",
    label: "Soporte IA",
    description: "Asistente de soporte con IA, conocimiento y casos",
    category: "ia",
    isActive: true,
    sortOrder: 19,
    metadata: {},
  },
  {
    key: "catalog",
    label: "Catálogo de plataforma",
    description:
      "Catálogos globales de features, capacidades, herramientas IA y límites",
    category: "administracion",
    isActive: true,
    sortOrder: 20,
    metadata: {},
  },
  {
    key: "superAdmin",
    label: "Super Admin",
    description:
      "Administración global: planes, políticas comerciales y configuración de plataforma",
    category: "administracion",
    isActive: true,
    sortOrder: 21,
    metadata: {},
  },
];

export const DEFAULT_APP_FEATURES_BY_PLAN: Record<string, string[]> = {
  FREE: ["dashboard", "customers", "products", "quotes", "settings"],
  STARTER: [
    "dashboard",
    "customers",
    "products",
    "quotes",
    "sales",
    "channels",
    "conversations",
    "agent",
    "reports",
    "settings",
  ],
  PRO: [
    "dashboard",
    "customers",
    "products",
    "quotes",
    "sales",
    "channels",
    "conversations",
    "agent",
    "reports",
    "integrations",
    "settings",
  ],
  ENTERPRISE: [
    "dashboard",
    "customers",
    "products",
    "quotes",
    "sales",
    "channels",
    "conversations",
    "agent",
    "reports",
    "integrations",
    "settings",
  ],
};

const FREE_CAPABILITIES = [
  "dashboard.view",
  "customers.view",
  "customers.detail",
  "customers.create",
  "customers.update",
  "customers.delete",
  "customers.history",
  "products.view",
  "products.detail",
  "products.create",
  "products.update",
  "products.changeStatus",
  "products.delete",
  "quotes.view",
  "quotes.detail",
  "quotes.create",
  "quotes.update",
  "quotes.send",
  "quotes.accept",
  "quotes.pdf",
  "settings.company",
  "settings.currency",
  "settings.timezone",
  "settings.branding",
  "settings.commercialPolicy",
];

const STARTER_CAPABILITIES = [
  ...FREE_CAPABILITIES,
  "sales.view",
  "sales.detail",
  "sales.cancel",
  "sales.delete",
  "sales.pdf",
  "channels.view",
  "channels.detail",
  "channels.create",
  "channels.update",
  "channels.changeStatus",
  "channels.delete",
  "channels.publicChat",
  "conversations.view",
  "conversations.messages",
  "conversations.reply",
  "conversations.claim",
  "conversations.reopen",
  "agent.configure",
  "agent.chat",
  "agent.productSearch",
  "agent.productDetails",
  "agent.customerLookup",
  "agent.customerHistory",
  "agent.customerUpdate",
  "agent.quoteHistory",
  "agent.quoteDetails",
  "agent.quoteDraft",
  "agent.quoteUpdate",
  "agent.quoteAccept",
  "agent.salesHistory",
  "agent.humanHandoff",
  "reports.view",
];

const PRO_CAPABILITIES = [
  ...STARTER_CAPABILITIES,
  "integrations.manage",
];

export const DEFAULT_APP_CAPABILITIES_BY_PLAN: Record<string, string[]> = {
  FREE: FREE_CAPABILITIES,
  STARTER: STARTER_CAPABILITIES,
  PRO: PRO_CAPABILITIES,
  ENTERPRISE: PRO_CAPABILITIES,
};